config/routes.rb
Rails.application.routes.draw do

  root 'goals#index'

  resources :goals do
    resources :todos
  end

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  has_many :todos
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :goal
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  def index
    @goals = Goal.all
  end

  def new
    @goal = Goal.new
  end

  def create
    @goal = Goal.new(goal_params)
    if @goal.save
      redirect_to root_path
      flash[:notice] = "Goal Successfully Created"
    else
      render :new
      flash[:notice] = "There was an error saving your goal"
    end
  end

  def show
    @goal = Goal.find(params[:id])
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])
    @goal.update(goal_params)
    if @goal.save
      flash[:notice] = "goal successfully saved"
      redirect_to goals_path
    else
      render :edit
      flash[:notice] = "There was an error saving your goal"
    end
  end

  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy
    redirect_to goals_path
    flash[:notice] = "delete successful"
  end

  private
  def goal_params
    params.require(:goal).permit(
      :name,
      :description,
      :due_date,
      :completed
    )
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_goal

  def new
    @todo = @goal.todos.new
  end

  def create
    @todo = @goal.todos.create(todo_params)
    if @todo.save
      redirect_to goal_path(@goal)
      flash[:notice] = "todo saved!"
    else
      flash[:notice] = "there was an error saving your todo"
    end
  end

  def edit
    @todo = @goal.todos.find(params[:id])
  end

  def update
    @todo = @goal.todos.find(params[:id])
    @todo.update(todo_params)
    if @todo.save
      flash[:notice] = "todo successfully saved!"
      redirect_to goal_path(@goal)
    else
      flash[:notice] = "todo could not be saved"
      render :edit
    end
  end

  def destroy
    @todo = @goal.todos.find(params[:id])
    @todo.destroy
    redirect_to goal_path(@goal)
  end

  private

  def todo_params
    params.require(:todo).permit(
    :title,
    :description
    )
  end

  def set_goal
    @goal = Goal.find(params[:goal_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/goals/_form.html.erb
<h1>form!</h1>

<%=form_for(@goal, html: {class: "form-horizontal"}) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :due_date %>
  <%= f.date_field :due_date %>

  <%= f.label "Completed?" %>
  <%= f.check_box :completed %>

  <%= f.submit "Submit Post", id: "submit-post-action" %>
<% end %>

app/views/goals/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Goals Index page AKA PASSION PLAN!!!!</h1>
    <div>
      <% @goals.each do |goal|%>
      <p><%= goal.name%></p>
      <p><%= goal.description%></p>
      <p><%= goal.due_date%></p>
      <p><%= goal.completed%></p>
      <p><%= link_to "Edit #{goal.name}", goal_path(goal), id:"update-goal-action" %><%= link_to "Delete #{goal.name}", goal_path(goal), method: :delete, id:"delete-goal-action" %></p>
      <% end %>
    </div>
    <%= link_to "Record New Goal", new_goal_path, class: "button", id: "new-goal-action" %>
  </body>
</html>

app/views/goals/new.html.erb
<h1>Record New Goal</h1>

<%= render 'form'%>

app/views/goals/show.html.erb
<h1>EDIT GOAL</h1>

<%= render 'form' %>

<% @goal.todos.each do |todo| %>
  <p><%=  todo.title %></p>
  <p><%=  todo.description %></p>
  <p><%=  todo.completed %></p>
  <%= link_to "edit this todo", edit_goal_todo_path(@goal, todo) %>
  <%= link_to "delete this todo", goal_todo_path(@goal, todo), method: :delete %>
<% end %>

<%= link_to "Create To Dos For This Goal", new_goal_todo_path(@goal)%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FunAddOnProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todos/_todo_form.html.erb
<%= form_for([@goal, @todo], html: {class: "form-horizontal"}) do |f| %>
  <%= f.label :title %>
  <%= f.text_area :title %>

  <%=f.label :description %>
  <%=f.text_area :description %>

  <%= f.submit %>
<% end %>

app/views/todos/edit.html.erb
<h1>EDIT YOUR TODO</h1>

<%= render 'todo_form' %>

app/views/todos/new.html.erb
<h1>NEW TODO FOR YOUR GOAL!</h1>

<%= render 'todo_form' %>